### PR TITLE
More modules, tips, and new distributions section.

### PR DESCRIPTION
**Pull request by nirgn975**
#1

### CODE REVIEW

**Comment by RoySegall** [comment]
I can't push; I remember you gave me permission, but anyway this is the missing parts:

```
- [How to install Drupal using Composer](http://whaaat.com/installing-drush-9-using-composer)
- [Using composer to set up Drupal 8](https://www.lullabot.com/articles/goodbye-drush-make-hello-composer)

```

**Comment by nirgn975** [comment]
@RoySegall Ready for review.

**Comment by RoySegall** [comment]
yalla! let's merge it

**Comment by nirgn975** [comment]
@RoySegall Be my guest

**Pull request merged**
